# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subscription_enable_lot'),
        ('report', '0002_reportsetting_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitAndLossAccountReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_root_categories_only', models.BooleanField(default=False)),
                ('show_zero_balance_ledgers', models.BooleanField(default=False)),
                ('show_zero_balance_categories', models.BooleanField(default=False)),
                ('show_ledgers_only', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_and_loss_account_settings', to='users.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccountReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_root_categories_only', models.BooleanField(default=False)),
                ('show_zero_balance_ledgers', models.BooleanField(default=False)),
                ('show_zero_balance_categories', models.BooleanField(default=False)),
                ('show_ledgers_only', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_account_settings', to='users.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TrialBalanceReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_root_categories_only', models.BooleanField(default=False)),
                ('show_zero_balance_ledgers', models.BooleanField(default=False)),
                ('show_zero_balance_categories', models.BooleanField(default=False)),
                ('show_ledgers_only', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_settings', to='users.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='reportsetting',
            name='company',
        ),
        migrations.DeleteModel(
            name='ReportSetting',
        ),
    ]
