# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subscription_enable_lot'),
        ('report', '0003_auto_20160620_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_root_categories_only', models.BooleanField(default=False)),
                ('show_zero_balance_ledgers', models.BooleanField(default=False)),
                ('show_zero_balance_categories', models.BooleanField(default=False)),
                ('show_ledgers_only', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet_settings', to='users.Company')),
            ],
        ),
    ]
