# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20160810_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='inventory_balance',
            field=models.FloatField(default=0),
        ),
    ]
