# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20160810_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_account', to='users.Company'),
        ),
    ]
