# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20160811_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='closing',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
