# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0009_auto_20151220_1554'),
        ('users', '0007_auto_20151229_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField()),
                ('receipt_on', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Party', verbose_name='Receipt From')),
            ],
        ),
        migrations.CreateModel(
            name='CashReceiptRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FloatField()),
                ('discount', models.FloatField()),
                ('cash_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.CashReceipt')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inventory.Sale')),
            ],
        ),
    ]
