# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0012_auto_20160217_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserow',
            name='tax',
            field=models.CharField(blank=True, choices=[('no', 'No Tax'), ('inclusive', 'Tax Inclusive'), ('exclusive', 'Tax Exclusive')], default='inclusive', max_length=10, null=True),
        ),
    ]
