# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0013_purchaserow_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserow',
            name='tax',
        ),
        migrations.AlterField(
            model_name='purchaserow',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
