# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0015_purchase_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
