# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0017_purchaseorder_purchaseorderrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderrow',
            name='budget_title_no',
        ),
    ]
