# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_pin_date'),
        ('voucher', '0018_remove_purchaseorderrow_budget_title_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
            preserve_default=False,
        ),
    ]
