# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0019_purchaseorder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Unit'),
        ),
    ]
