# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0020_auto_20160330_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderrow',
            name='vattable',
        ),
    ]
