# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0021_remove_purchaseorderrow_vattable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='PurchaseVoucher',
        ),
        migrations.RenameModel(
            old_name='PurchaseRow',
            new_name='PurchaseVoucherRow',
        ),
    ]
