# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_auto_20160306_1353'),
        ('voucher', '0023_vouchersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax',
            field=models.CharField(blank=True, choices=[('no', 'No Tax'), ('inclusive', 'Tax Inclusive'), ('exclusive', 'Tax Exclusive')], default='inclusive', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.TaxScheme'),
        ),
    ]
