# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0025_salerow_tax_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
