# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import njango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_auto_20160506_1250'),
        ('users', '0025_auto_20160427_1350'),
        ('voucher', '0027_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField(blank=True, null=True)),
                ('date', njango.fields.BSDateField(default=njango.fields.today)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='ledger.Account')),
                ('pay_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_and_bank', to='ledger.Account')),
            ],
        ),
    ]
