# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0028_expense_expenserow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserow',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.Expense'),
        ),
    ]
