# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0030_auto_20160506_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserow',
            name='expense_row',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.Expense'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenserow',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='ledger.Account'),
        ),
    ]
