# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0032_purchaseorder_purchase_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
