# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0033_auto_20160515_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
