# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0034_auto_20160515_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderrow',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
