# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0035_purchaseorderrow_fulfilled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vouchersetting',
            old_name='invoice_default_tax_application_type',
            new_name='sale_default_tax_application_type',
        ),
        migrations.RenameField(
            model_name='vouchersetting',
            old_name='invoice_default_tax_scheme',
            new_name='sale_default_tax_scheme',
        ),
        migrations.RemoveField(
            model_name='vouchersetting',
            name='voucher_number_start_date',
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_suggest_by_item',
            field=models.BooleanField(default=True, verbose_name='Suggest rate by item'),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_suggest_by_party_item',
            field=models.BooleanField(default=True, verbose_name='Suggest rate by item by party'),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_suggest_by_item',
            field=models.BooleanField(default=True, verbose_name='Suggest rate by item'),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_suggest_by_party_item',
            field=models.BooleanField(default=True, verbose_name='Suggest rate by item by party'),
        ),
    ]
