# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0036_auto_20160529_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='salerow',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.Item'),
        ),
    ]
