# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0037_auto_20160530_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersetting',
            name='add_expense_cost_to_purchase',
            field=models.BooleanField(default=True, verbose_name='Add expense cost'),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='enable_expense_in_purchase',
            field=models.BooleanField(default=True, verbose_name='Enable Expense'),
        ),
    ]
