# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ledger', '0008_auto_20160528_1350'),
        ('voucher', '0038_auto_20160602_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account')),
            ],
        ),
    ]
