# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0039_tradeexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_voucher', to='voucher.PurchaseOrder'),
        ),
    ]
