# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0039_tradeexpense'),
        ('voucher', '0041_auto_20160531_1126'),
    ]

    operations = [
    ]
