# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0040_purchasevoucher_purchase_order'),
        ('voucher', '0042_merge'),
    ]

    operations = [
    ]
