# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0043_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_print_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_print_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_print_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_print_lot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_print_oem_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_print_sn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_voucher_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_voucher_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_voucher_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_voucher_lot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_voucher_oem_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_voucher_sn',
            field=models.BooleanField(default=True),
        ),
    ]
