# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0043_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_number',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
