# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0044_auto_20160610_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vouchersetting',
            old_name='purchase_print_oem_code',
            new_name='purchase_print_oem_number',
        ),
        migrations.RenameField(
            model_name='vouchersetting',
            old_name='purchase_voucher_oem_code',
            new_name='purchase_voucher_oem_number',
        ),
    ]
