# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0045_purchasevoucherrow_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasevoucherrow',
            name='location',
        ),
    ]
