# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0045_auto_20160610_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_print_tax_scheme',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='purchase_voucher_tax_scheme',
            field=models.BooleanField(default=True),
        ),
    ]
