# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0046_remove_purchasevoucherrow_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
