# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0046_auto_20160610_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchersetting',
            name='discount_on_each_purchase_particular',
        ),
    ]
