# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_location'),
        ('voucher', '0047_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucherrow',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
        ),
    ]
