# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0047_remove_vouchersetting_discount_on_each_purchase_particular'),
        ('voucher', '0044_auto_20160606_1307'),
    ]

    operations = [
    ]
