# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0048_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchersetting',
            name='discount_on_each_invoice_particular',
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_print_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_print_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_print_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_print_lot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_print_oem_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_print_sn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_print_tax_scheme',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_voucher_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_voucher_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_voucher_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_voucher_lot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_voucher_oem_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_voucher_sn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchersetting',
            name='sale_voucher_tax_scheme',
            field=models.BooleanField(default=True),
        ),
    ]
