# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0050_auto_20160610_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salefromlocation',
            name='sale_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_locations', to='voucher.SaleRow'),
        ),
    ]
