# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

# def add_lot(apps, schema_editor):
#     from apps.voucher.models import Lot, LotItemDetail
#     lots = Lot.objects.all()
#     if lots:
#         lot = lots[0]
#         for l_d in LotItemDetail.objects.all():
#             l_d.lot = lot
#             l_d.save()

def empty_lotitemdetails(apps, schema_editor):
    from apps.voucher.models import LotItemDetail
    LotItemDetail.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0051_auto_20160610_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='lot_item_details',
        ),
        migrations.RunPython(empty_lotitemdetails),
        migrations.AddField(
            model_name='lotitemdetail',
            name='lot',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='lot_item_details', to='voucher.Lot'),
            preserve_default=False,
        ),
        # migrations.RunPython(add_lot),
        #
        # migrations.AlterField(
        #     model_name='lotitemdetail',
        #     name='lot',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
        #                             related_name='lot_item_details', to='voucher.Lot'),
        # ),
    ]
