# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0052_auto_20160610_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salefromlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.Location'),
        ),
    ]
