# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0053_auto_20160611_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_puchase_vouchers', to='inventory.Location'),
        ),
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lot_purchase_vouchers', to='voucher.Lot'),
        ),
    ]
