# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0044_auto_20160606_1307'),
        ('voucher', '0054_auto_20160611_1003'),
    ]

    operations = [
    ]
