# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0057_auto_20160613_1347'),
        ('voucher', '0057_auto_20160613_1331'),
    ]

    operations = [
    ]
