# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0058_merge'),
        ('voucher', '0058_auto_20160613_1524'),
    ]

    operations = [
    ]
