# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_account_default'),
        ('voucher', '0061_auto_20160614_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipt', to='ledger.Account'),
        ),
    ]
