# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-05 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0063_cashpayment_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashReceipt',
            new_name='CreditVoucher',
        ),
        migrations.RenameModel(
            old_name='CashPaymentRow',
            new_name='CreditVoucherRow',
        ),
        migrations.RenameModel(
            old_name='CashPayment',
            new_name='DebitVoucher',
        ),
        migrations.RenameModel(
            old_name='CashReceiptRow',
            new_name='DebitVoucherRow',
        ),
        migrations.RenameField(
            model_name='creditvoucherrow',
            old_name='payment',
            new_name='receipt',
        ),
        migrations.RenameField(
            model_name='debitvoucherrow',
            old_name='receipt',
            new_name='payment',
        ),
        migrations.AddField(
            model_name='creditvoucherrow',
            name='cash_receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.CreditVoucher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debitvoucherrow',
            name='cash_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.DebitVoucher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditvoucherrow',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='voucher.Sale'),
        ),
        migrations.AlterField(
            model_name='debitvoucherrow',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='voucher.PurchaseVoucher'),
        ),
        migrations.RemoveField(
            model_name='creditvoucherrow',
            name='cash_payment',
        ),
        migrations.AlterUniqueTogether(
            name='creditvoucherrow',
            unique_together=set([('invoice', 'cash_receipt')]),
        ),
        migrations.RemoveField(
            model_name='debitvoucherrow',
            name='cash_receipt',
        ),
        migrations.AlterUniqueTogether(
            name='debitvoucherrow',
            unique_together=set([('invoice', 'cash_payment')]),
        ),
    ]
