# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0066_auto_20160707_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersetting',
            name='unique_voucher_number_by_fy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vouchersetting',
            name='unique_voucher_number',
            field=models.BooleanField(default=False),
        ),
    ]
