# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160519_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='interconnection_among_branches',
            field=models.BooleanField(default=True),
        ),
    ]
