# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 10:01
from __future__ import unicode_literals

from django.db import migrations


def create_groups(apps, schema_editor):
    from django.contrib.auth.models import Group
    Group.objects.create(name='Cashier')
    Group.objects.create(name='Stockist')


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_subscription_interconnection_among_branches'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
