# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_companysetting_unique_voucher_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysetting',
            name='voucher_number_restart_days',
        ),
        migrations.RemoveField(
            model_name='companysetting',
            name='voucher_number_restart_months',
        ),
        migrations.RemoveField(
            model_name='companysetting',
            name='voucher_number_restart_years',
        ),
    ]
