# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160604_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enable_locations',
            field=models.BooleanField(default=False),
        ),
    ]
