# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_subscription_enable_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enable_lot',
            field=models.BooleanField(default=False),
        ),
    ]
