# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160124_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='discount_on_voucher',
            field=models.BooleanField(default=True),
        ),
    ]
