# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_companysetting_discount_on_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='discount_on_voucher_row',
            field=models.BooleanField(default=False),
        ),
    ]
