# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160825_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
