# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160309_1737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together=set([('company', 'used_by')]),
        ),
    ]
