# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 09:08
from __future__ import unicode_literals

from django.db import migrations
import njango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20160311_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='date',
            field=njango.fields.BSDateField(blank=True, null=True),
        ),
    ]
