# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_pin_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysetting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companysetting',
            name='invoice_default_tax_scheme',
        ),
        migrations.RemoveField(
            model_name='companysetting',
            name='purchase_default_tax_scheme',
        ),
        migrations.DeleteModel(
            name='CompanySetting',
        ),
    ]
