# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_auto_20160506_1250'),
        ('users', '0025_auto_20160427_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_party', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Party')),
            ],
        ),
    ]
