# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20160512_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.Company'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_party',
            field=models.BooleanField(default=False, verbose_name=b'Also create party for a barnch'),
        ),
    ]
