# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20160512_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_party',
            field=models.BooleanField(default=False, verbose_name=b'Also create party for a branch'),
        ),
    ]
