# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160519_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description_ne',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_ne',
        ),
    ]
