# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20160610_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contains',
            field=models.ManyToManyField(blank=True, to='inventory.LocationContain'),
        ),
    ]
