# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20160610_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='contains',
        ),
        migrations.AddField(
            model_name='locationcontain',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='inventory.Location'),
            preserve_default=False,
        ),
    ]
