# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20160610_1748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationcontain',
            unique_together=set([('location', 'item')]),
        ),
    ]
