# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20160611_1007'),
        ('inventory', '0005_auto_20160610_1123'),
    ]

    operations = [
    ]
