# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
