# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subscription_enable_lot'),
        ('inventory', '0015_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
            preserve_default=False,
        ),
    ]
