# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_location_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcontain',
            name='qty',
            field=models.FloatField(),
        ),
    ]
