# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20160705_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaccount',
            name='total_cost',
            field=models.FloatField(default=0, null=True),
        ),
    ]
