# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_inventoryaccount_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryaccount',
            name='total_cost',
        ),
    ]
