# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_inventoryaccount_total_cost'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='itemcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
            ],
        ),
    ]
