# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 06:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_journalvoucher_journalvoucherrow'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
