# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20151225_1435'),
        ('ledger', '0003_auto_20151229_1224'),
    ]

    operations = [
    ]
