# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20160528_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.Company'),
        ),
    ]
