# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 09:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20160106_1434'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
