# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_pin_date'),
        ('ledger', '0009_auto_20160225_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='related_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
        ),
        migrations.AlterField(
            model_name='party',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='users.Company'),
        ),
    ]
