# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_category_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
