# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20160330_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together=set([('company', 'related_company')]),
        ),
    ]
