# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_auto_20160815_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name=b'email address'),
        ),
    ]
