# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_auto_20160428_1616'),
        ('ledger', '0021_auto_20160428_1706'),
    ]

    operations = [
    ]
