# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[(b'Customer', b'Customer'), (b'Supplier', b'Supplier'), (b'Customer/Supplier', b'Customer/Supplier')], default=b'Customer/Supplier', max_length=17),
        ),
    ]
