# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxscheme',
            name='full_name',
        ),
    ]
