# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_remove_taxscheme_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxscheme',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
