# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_auto_20160523_1914'),
        ('tax', '0002_auto_20160519_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxscheme',
            name='payable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tax_payable', to='ledger.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxscheme',
            name='receivable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tax_receivable', to='ledger.Account'),
            preserve_default=False,
        ),
    ]
