# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20160304_1802'),
        ('ledger', '0009_auto_20160225_1535'),
        ('tax', '0003_taxscheme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyTaxPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tax_application_type', models.CharField(blank=True, choices=[(b'no', b'No Tax'), (b'inclusive', b'Tax Inclusive'), (b'exclusive', b'Tax Exclusive'), (b'no-peference', b'No Perference')], default=b'inclusive', max_length=15, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_preference', to='ledger.Party')),
                ('tax_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.TaxScheme')),
            ],
        ),
    ]
