# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_auto_20160306_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partytaxpreference',
            name='default_tax_application_type',
            field=models.CharField(blank=True, choices=[(b'no', b'No Tax'), (b'inclusive', b'Tax Inclusive'), (b'exclusive', b'Tax Exclusive'), (b'no-preference', b'No Preference')], default=b'inclusive', max_length=15, null=True),
        ),
    ]
