# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20160215_1424'),
        ('payroll', '0002_auto_20160204_1234'),
    ]

    operations = [
    ]
